# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'iTSC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iTSC

pod 'OHMySQL'
pod 'Charts'

end
